// makes it so the menus "drop down" when you hover over the nav bar in the appropriate places...
// or, really, so that they appear & disappear... unhide & hide... 
        
    // Flag to indicate if a drop-down menu is visible... (taken from Web App Dev book pg 268, with modifications...)
    var isShowing = false;
        
    // Reference to the current drop-down menu... 
    var dropDownMenu = null;        // what??
        
    // Hide any currently-visible drop-down menu and set the 'isShowing' variable flag up there...
    function hide() {
        if (isShowing) dropDownMenu.style.visibility = "hidden";
        isShowing = false;              // done just like on page 268 of Web App Dev book, just modified with my var names...
    }                           // but moved it above show(id) function, since it's called in that function... seems to make more sense to me... 
        
    // Show the drop-down menu with the given id... and set the 'isShowing' variable flag up there... 
    function show(id)   {       // note this is the function called 'onmouseover' in the html... 
        hide();     // first hide any previously-showing drop-down menu...
        dropDownMenu = document.getElementById(id);     // assigns the DOM element to the variable...
        if (dropDownMenu !== null)   {                   // (id) is filled in with the id stated in the html when function is called... 
            dropDownMenu.style.visibility = "visible";
            isShowing = true;
        }
    }
        